using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ServiceReference
{
    using System.Runtime.Serialization;
    using System;

    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Этот код создан программой.
    //     Исполняемая версия:4.0.30319.42000
    //
    //     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
    //     повторной генерации кода.
    // </auto-generated>
    //------------------------------------------------------------------------------



    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IService")]
    public interface IService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService/Method1", ReplyAction = "http://tempuri.org/IService/Method1Response")]
        string Method1(string x);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService/Method1", ReplyAction = "http://tempuri.org/IService/Method1Response")]
        System.Threading.Tasks.Task<string> Method1Async(string x);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService/Method2", ReplyAction = "http://tempuri.org/IService/Method2Response")]
        string Method2(string x);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService/Method2", ReplyAction = "http://tempuri.org/IService/Method2Response")]
        System.Threading.Tasks.Task<string> Method2Async(string x);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : IService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<IService>, IService
    {

        public ServiceClient()
        {
        }

        public ServiceClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public ServiceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public string Method1(string x)
        {
            return base.Channel.Method1(x);
        }

        public System.Threading.Tasks.Task<string> Method1Async(string x)
        {
            return base.Channel.Method1Async(x);
        }

        public string Method2(string x)
        {
            return base.Channel.Method2(x);
        }

        public System.Threading.Tasks.Task<string> Method2Async(string x)
        {
            return base.Channel.Method2Async(x);
        }
    }

}
